services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports: 
      - 15672:15672
      - 5672:5672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - datahive_net
    logging:
      driver: none

  worker_1:
      build:
        context: ./worker
        dockerfile: Dockerfile
      restart: always
      networks:
        - datahive_net

  meteorct:
    build:
      context: ./frontend2
      dockerfile: Dockerfile
    restart: always
    links:
      - mongo
    ports:
      - 3000:3000
    networks:
      - datahive_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./frontend2/app:/app
    environment:
      - MONGO_URL=mongodb://mongo/meteor

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./frontend2/app/.meteor/local/db:/data/db
    networks:
      - datahive_net
    logging:
      driver: none

networks:
  datahive_net:
    driver: bridge


# volume mapping
